### ISSUE TITLE
undefined method `sass' for #<Rails::Engine::Configuration:0x00000003bc3268> when executing RAILS_ENV=production rake --trace db:migrate

### ISSUE THREAD

**Issue by ckruse** [anjlab/bootstrap-rails#26]
When I execute RAILS_ENV=production rake --trace db:migrate I get the following error message:

```
ckruse@lin /var/www/noodles.termitel.de $ RAILS_ENV=production rake --trace db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `sass' for #<Rails::Engine::Configuration:0x00000003bc3268>
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/railtie/configuration.rb:85:in `method_missing'
/usr/local/lib64/ruby/gems/1.9.1/gems/anjlab-bootstrap-rails-2.1.0.0/lib/bootstrap-rails/engine.rb:5:in `block in <class:Engine>'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/noodles.termitel.de/config/environment.rb:6:in `<top (required)>'
/usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
/usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/lib64/ruby/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:103:in `require_environment!'
/usr/local/lib64/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:295:in `block (2 levels) in initialize_tasks'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib64/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/lib64/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/local/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```

Same happens with every HTTP request. Ruby 1.9.3, Rails 3.2.8 – I have to downgrade to 2.0.4

**Comment by ckruse** [comment]
Moving gem 'sass-rails' out of the :asset group resolves this issue… an autoloading problem?

**Comment by coreyward** [comment]
Do you have the bootstrap-rails gem in your assets group, or ungrouped?

**Comment by ckruse** [comment]
ungrouped

No, not true: grouped

**Comment by coreyward** [comment]
That's probably your issue — you are trying to load `anjlab-bootstrap-rails` without a core dependency. Move it into the same group, immediately after `sass-rails` and you should be golden.

**Comment by ckruse** [comment]
Hm, I will try it out tomorrow. Thanks for your help!

**Comment by ckruse** [comment]
It was indeed a dependency problem. Moving rails-sass and anjlab-bootstrap-rails to the same group fixed the problem. Thanks.

**Comment by yury** [comment]
v2.1.0.3 should be ok. Even if anjlab-bootstrap-rails in different group.
