### ISSUE TITLE
Assets:precompile fails: Invalid US-ASCII character "\xC2"

### ISSUE THREAD

**Issue by vinceve** [anjlab/bootstrap-rails#66]
When I'm trying to deploy I get this error:

```
Invalid US-ASCII character "\xC2"
  (in /home/vince/Programming/projects/ruby/myproject/app/assets/stylesheets/application.scss)
(sass):9
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/engine.rb:373:in `block in check_encoding!'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:603:in `rescue in block in check_encoding'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:600:in `block in check_encoding'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:599:in `each'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:599:in `each_with_index'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:599:in `check_encoding'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/util.rb:653:in `check_sass_encoding'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/engine.rb:372:in `check_encoding!'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/engine.rb:339:in `_to_tree'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/engine.rb:315:in `_render'
/home/vince/.gem/ruby/1.9.3/gems/sass-3.2.10/lib/sass/engine.rb:262:in `render'
/home/vince/.gem/ruby/1.9.3/gems/sass-rails-3.2.5/lib/sass/rails/compressor.rb:8:in `compress'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/compressors.rb:74:in `compress'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/processing.rb:243:in `block in css_compressor='
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/processor.rb:29:in `call'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/processor.rb:29:in `evaluate'
/home/vince/.gem/ruby/1.9.3/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:26:in `initialize'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:19:in `block in compile'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/home/vince/.gem/ruby/1.9.3/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:18:in `compile'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:56:in `internal_precompile'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/opt/rubies/ruby-1.9.3-p448/bin/ruby /home...]
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/home/vince/.gem/ruby/1.9.3/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by kjakm** [comment]
Can you show your `application.scss` It sounds like you have an invalid character in that file causing the error.

**Comment by vinceve** [comment]
Hi I needed to add @charset "UTF-8"; in my application.scss that fixed the problem.
