### ISSUE TITLE
Undefined variable: "$baseline"?

### ISSUE THREAD

**Issue by millisami** [anjlab/bootstrap-rails#8]
When using with Rails 3.1.3 app, works on dev env.

But when I try to precompile, it blows out.

What might be the issue?

```
RAILS_ENV=development be rake assets:precompile -t                                                              
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/Users/millisami/.rvm/rubies/ruby-1.9.2-head/bin/ruby /Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bin/rake assets:precompile:all RAILS_ENV=development RAILS_GROUPS=assets --trace
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
rake aborted!
Undefined variable: "$baseline".
  (in /Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bundler/gems/bootstrap-rails-7e49c5538de4/vendor/assets/stylesheets/forms.scss)
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bundler/gems/bootstrap-rails-7e49c5538de4/vendor/assets/stylesheets/forms.scss:10
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/script/variable.rb:50:in `_perform'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/script/node.rb:40:in `perform'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:214:in `visit_prop'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:234:in `visit_rule'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/tree/root_node.rb:20:in `render'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/engine.rb:300:in `_render'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-3.1.11/lib/sass/engine.rb:247:in `render'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sass-rails-3.1.5/lib/sass/rails/template_handlers.rb:95:in `evaluate'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/context.rb:175:in `block in evaluate'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in `evaluate'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:171:in `build_dependency_context_and_body'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:135:in `dependency_context'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_assets'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:141:in `dependency_paths'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:61:in `mtime'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/asset.rb:58:in `block in encode_with'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/asset.rb:57:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/asset.rb:57:in `encode_with'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:43:in `encode_with'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/caching.rb:52:in `cache_asset'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/environment.rb:82:in `build_asset'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/trail.rb:102:in `find_asset_in_path'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:101:in `find_asset'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/environment.rb:72:in `find_asset'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/static_compiler.rb:20:in `block in compile'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:151:in `block in each_logical_path'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:139:in `block (2 levels) in each_file'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:129:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:129:in `each_entry'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:137:in `block in each_file'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:136:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:136:in `each_file'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/sprockets-2.0.3/lib/sprockets/base.rb:149:in `each_logical_path'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/static_compiler.rb:18:in `compile'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:52:in `internal_precompile'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:66:in `block (3 levels) in <top (required)>'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/millisami/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:56:in `block (3 levels) in <top (required)>'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/millisami/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bin/rake:19:in `load'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bin/rake:19:in `<main>'
Tasks: TOP => assets:precompile:primary
rake aborted!
Command failed with status (1): [/Users/millisami/.rvm/rubies/ruby-1.9.2-he...]
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `call'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `sh'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils.rb:80:in `ruby'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `ruby'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:9:in `ruby_rake_task'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:17:in `invoke_or_reboot_rake_task'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/actionpack-3.1.3/lib/sprockets/assets.rake:25:in `block (2 levels) in <top (required)>'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/millisami/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bin/rake:19:in `load'
/Users/millisami/.rvm/gems/ruby-1.9.2-head@cwi/bin/rake:19:in `<main>'
Tasks: TOP => assets:precompile
RAILS_ENV=development bundle exec rake assets:precompile -t  13.88s user 2.85s system 87% cpu 19.114 total
```

**Comment by yury** [comment]
Can you gist your application.css.scss?

If you include bootstrap via `//=require bootstrap` try to use `@import "bootstrap.scss";` instead

**Comment by millisami** [comment]
I tried with that too, but still the same error:

Following are the files:

``` ruby
#Gemfile
gem 'rails', '3.1.3'
...
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :tag => 'v0.12.alpha.2'
  gem 'compass-susy-plugin', :require => 'susy'
  gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails',
                                  :git => 'git://github.com/anjlab/bootstrap-rails.git'
end
...
```

``` scss
#app/assets/stylesheets/application.css.scss
@import "bootstrap.scss";
```

``` scss
#app/assets/stylesheets/bootstrap.scss
// Create app/assets/stylesheets/bootstrap.scss
// CSS Reset
@import "reset.scss";

// Core variables and mixins
@import "variables.scss"; // Modify this for custom colors, font-sizes, etc

$linkColor: red; // Make all links red

@import "mixins.scss";

// Grid system and page structure
@import "scaffolding.scss";

// Styled patterns and elements
@import "type.scss";
@import "forms.scss";
@import "tables.scss";
@import "patterns.scss";
```

**Comment by millisami** [comment]
Any progress on this issue?

**Comment by yury** [comment]
@millisami, can't reproduce...

Still trying to repro your problem https://gist.github.com/1435079

**Comment by yury** [comment]
@millisami, can you create test project on github?

**Comment by millisami** [comment]
I tweaked and tried with several modifications and right now its working.
Couldn't figure out what was wrong. But now its working!

**Comment by samer** [comment]
in application.css, remove the "require_tree" line (which requires all the scss files in that directory). Only include bootstrap.scss.

In other words, delete this:

```
*= require_tree
```

Replace with this:

```
*= require bootstrap.scss
```
